import React, { useEffect, useRef, useState } from 'react';
import { useSocket } from '../context/SocketContext';

const BUFFER_SIZE = 100;

function lastDigit(tick) {
  const decimals = tick.pip_size ?? 2;
  const str = tick.quote.toFixed(decimals).replace('.', '');
  return Number(str[str.length - 1]);
}

function useDigitStats(symbol) {
  const { subscribeTicks } = useSocket();
  const bufferRef = useRef([]);
  const [stats, setStats] = useState(null);

  useEffect(() => {
    bufferRef.current = [];
    const unsubscribe = subscribeTicks(symbol, (tick) => {
      const digit = lastDigit(tick);
      bufferRef.current = [...bufferRef.current.slice(-(BUFFER_SIZE - 1)), digit];
      const buf = bufferRef.current;

      const counts = new Array(10).fill(0);
      buf.forEach((d) => counts[d]++);
      const over = buf.filter((d) => d > 5).length;
      const under = buf.filter((d) => d < 5).length;
      const odd = buf.filter((d) => d % 2 === 1).length;
      const even = buf.filter((d) => d % 2 === 0).length;
      const mostDigit = counts.indexOf(Math.max(...counts));
      const leastDigit = counts.indexOf(Math.min(...counts));

      setStats({
        sampleSize: buf.length,
        overPct: (100 * over) / buf.length,
        underPct: (100 * under) / buf.length,
        oddPct: (100 * odd) / buf.length,
        evenPct: (100 * even) / buf.length,
        mostDigit,
        leastDigit,
      });
    });
    return unsubscribe;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [symbol]);

  return stats;
}

function SignalCard({ symbol, label }) {
  const stats = useDigitStats(symbol);

  return (
    <div className="panel signal-card">
      <div className="signal-top">
        <span className="symbol-name">{label}</span>
        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
          {stats ? `${stats.sampleSize} ticks` : 'loading…'}
        </span>
      </div>

      {stats ? (
        <div className="signal-stat-grid">
          <div className="signal-stat">
            <div className="stat-label">Over 5</div>
            <div className="stat-value mono">{stats.overPct.toFixed(1)}%</div>
          </div>
          <div className="signal-stat">
            <div className="stat-label">Under 5</div>
            <div className="stat-value mono">{stats.underPct.toFixed(1)}%</div>
          </div>
          <div className="signal-stat">
            <div className="stat-label">Odd</div>
            <div className="stat-value mono">{stats.oddPct.toFixed(1)}%</div>
          </div>
          <div className="signal-stat">
            <div className="stat-label">Even</div>
            <div className="stat-value mono">{stats.evenPct.toFixed(1)}%</div>
          </div>
          <div className="signal-stat">
            <div className="stat-label">Most frequent</div>
            <div className="stat-value mono">{stats.mostDigit}</div>
          </div>
          <div className="signal-stat">
            <div className="stat-label">Least frequent</div>
            <div className="stat-value mono">{stats.leastDigit}</div>
          </div>
        </div>
      ) : (
        <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>Collecting ticks…</p>
      )}

      <p className="signal-caption">
        Historical last-digit frequency over the most recent ticks. Synthetic indices are generated by a verified
        random number generator, so this describes what already happened - it is not a forecast of what comes next.
      </p>
    </div>
  );
}

export default function SignalsPanel({ symbols }) {
  if (!symbols.length) {
    return <p style={{ color: 'var(--text-muted)', fontSize: 14 }}>Connect your account to see live market signals.</p>;
  }
  return (
    <div className="signals-grid">
      {symbols.map((s) => (
        <SignalCard key={s.symbol} symbol={s.symbol} label={s.display_name} />
      ))}
    </div>
  );
}
